name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Pack the resol dir as a zip and upload to the release
      - name: ZIP resol Dir
        run: |
          cd ${{ github.workspace }}/custom_components/resol
          zip resol.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/resol/resol.zip
          asset_name: resol.zip
          tag: ${{ github.ref }}
          overwrite: true
